vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: /content/media
            upload_destination: '%kernel.project_dir%/uploads/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 'owner' }
